spring:
  application:
    name: delayQuery

spring:
  rabbitmq:
    host: rabbit地址
    port: 5673
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        retry:
          max-attempts: 5 #最大重试次数
          initial-interval: 1000ms #重试间隔时间（单位毫秒）
          enabled: true #是否开启消费者重试（为false时关闭消费者重试，这时消费端代码异常会一直重复收到消息）
        default-requeue-rejected: false   #重试次数超过上面的设置之后是否丢弃（false不丢弃时需要写相应代码将该消息加入死信队列）